/**
 * @file Defines common error codes for standardized error handling.
 * @Requirement REQ-14-006
 */

export const enum CommonErrorCodes {
  // General Errors
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  NETWORK_ERROR = 'NETWORK_ERROR',
  TIMEOUT_ERROR = 'TIMEOUT_ERROR',

  // Validation & Input Errors (400-level)
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  INVALID_PAYLOAD = 'INVALID_PAYLOAD',
  MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD',
  INVALID_PARAM = 'INVALID_PARAM',
  INVALID_QUERY_PARAM = 'INVALID_QUERY_PARAM',
  INVALID_FORMAT = 'INVALID_FORMAT', // e.g. invalid email format
  VALUE_OUT_OF_RANGE = 'VALUE_OUT_OF_RANGE',
  MAX_LENGTH_EXCEEDED = 'MAX_LENGTH_EXCEEDED',
  MIN_LENGTH_NOT_MET = 'MIN_LENGTH_NOT_MET',

  // Authentication & Authorization Errors (401, 403)
  UNAUTHENTICATED = 'UNAUTHENTICATED', // Missing or invalid credentials
  UNAUTHORIZED = 'UNAUTHORIZED', // Valid credentials, but insufficient permissions
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  MFA_REQUIRED = 'MFA_REQUIRED',
  ACCESS_DENIED = 'ACCESS_DENIED',

  // Resource Errors (404, 409)
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_CONFLICT = 'RESOURCE_CONFLICT', // e.g., version mismatch
  RESOURCE_ARCHIVED = 'RESOURCE_ARCHIVED',
  OPERATION_NOT_ALLOWED_ON_RESOURCE = 'OPERATION_NOT_ALLOWED_ON_RESOURCE',

  // Rate Limiting / Quota Errors (429)
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  QUOTA_EXCEEDED = 'QUOTA_EXCEEDED',

  // Configuration Errors
  CONFIGURATION_ERROR = 'CONFIGURATION_ERROR',
  MISSING_CONFIGURATION = 'MISSING_CONFIGURATION',

  // Database Errors
  DATABASE_ERROR = 'DATABASE_ERROR',
  DATABASE_CONNECTION_ERROR = 'DATABASE_CONNECTION_ERROR',
  TRANSACTION_FAILED = 'TRANSACTION_FAILED',
  ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND', // Specific to DB operations

  // External Service Errors
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
  EXTERNAL_SERVICE_TIMEOUT = 'EXTERNAL_SERVICE_TIMEOUT',
  EXTERNAL_SERVICE_UNAVAILABLE = 'EXTERNAL_SERVICE_UNAVAILABLE',
}