/**
 * @description Standardized error codes for the application.
 * REQ-14-006
 */
export const enum ErrorCodes {
  // General Errors
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  NETWORK_ERROR = 'NETWORK_ERROR',
  TIMEOUT_ERROR = 'TIMEOUT_ERROR',

  // Validation & Input Errors (400-499)
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  INVALID_PAYLOAD = 'INVALID_PAYLOAD',
  MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD',
  INVALID_PARAMETER = 'INVALID_PARAMETER', // For query/path params

  // Authentication & Authorization Errors (401, 403)
  UNAUTHENTICATED = 'UNAUTHENTICATED', // Missing or invalid credentials
  UNAUTHORIZED = 'UNAUTHORIZED', // Insufficient permissions
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  FORBIDDEN_RESOURCE = 'FORBIDDEN_RESOURCE',

  // Resource Errors (404, 409)
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
  CONFLICT = 'CONFLICT', // General conflict, e.g., optimistic locking

  // Server-Side Errors (500-599)
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR = 'DATABASE_ERROR',
  CONFIGURATION_ERROR = 'CONFIGURATION_ERROR',
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',

  // Feature Flag Errors
  FEATURE_NOT_ENABLED = 'FEATURE_NOT_ENABLED',

  // Specific Business Logic Errors (Examples - to be defined in respective domains)
  // CAMPAIGN_CREATION_FAILED = 'CAMPAIGN_CREATION_FAILED',
  // PRODUCT_OUT_OF_STOCK = 'PRODUCT_OUT_OF_STOCK',
}