export enum BidStrategyType {
  MANUAL_CPC = 'MANUAL_CPC',
  MANUAL_CPM = 'MANUAL_CPM',
  MAXIMIZE_CONVERSIONS = 'MAXIMIZE_CONVERSIONS',
  TARGET_CPA = 'TARGET_CPA',
  MAXIMIZE_CLICKS = 'MAXIMIZE_CLICKS',
  TARGET_ROAS = 'TARGET_ROAS',
  AUTOMATED_BIDDING = 'AUTOMATED_BIDDING',
}