export enum TargetingType {
  DEMOGRAPHICS = 'DEMOGRAPHICS',
  INTERESTS = 'INTERESTS',
  BEHAVIORS = 'BEHAVIORS',
  CUSTOM_AUDIENCE = 'CUSTOM_AUDIENCE',
  LOOKALIKE_AUDIENCE = 'LOOKALIKE_AUDIENCE',
  LOCATION = 'LOCATION',
  DEVICE = 'DEVICE',
  PRODUCT_IDS = 'PRODUCT_IDS', // Added from SDS section 2.4
  PROMOTION_IDS = 'PROMOTION_IDS', // Added from SDS section 2.4
}