export enum ShippingProductType {
  GENERAL = 'GENERAL',
  FRAGILE = 'FRAGILE',
  HAZARDOUS = 'HAZARDOUS',
  PERISHABLE = 'PERISHABLE',
  ELECTRONICS = 'ELECTRONICS',
  APPAREL = 'APPAREL',
  BOOKS = 'BOOKS',
  OTHER = 'OTHER',
}