export enum CommissionStatus {
  PENDING_CALCULATION = 'PENDING_CALCULATION',
  CALCULATED = 'CALCULATED',
  PENDING_PAYOUT = 'PENDING_PAYOUT',
  PAID = 'PAID',
  DISPUTED = 'DISPUTED',
  CLAWED_BACK = 'CLAWED_BACK',
  CANCELLED = 'CANCELLED',
}