export enum AppReviewStatus {
  PENDING_REVIEW = 'PENDING_REVIEW',
  IN_REVIEW = 'IN_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED_WITH_FEEDBACK = 'REJECTED_WITH_FEEDBACK',
  CHANGES_REQUESTED = 'CHANGES_REQUESTED',
}