export enum AppInstallationStatus {
  INSTALLING = 'INSTALLING',
  INSTALLED = 'INSTALLED',
  UNINSTALLING = 'UNINSTALLING',
  UNINSTALLED = 'UNINSTALLED',
  FAILED_INSTALL = 'FAILED_INSTALL',
  FAILED_UNINSTALL = 'FAILED_UNINSTALL',
}