export enum FeatureKey {
  // Limit-based features
  MAX_PRODUCT_CATALOGS = 'MAX_PRODUCT_CATALOGS',
  MAX_ACTIVE_CAMPAIGNS = 'MAX_ACTIVE_CAMPAIGNS',
  MAX_AFFILIATES = 'MAX_AFFILIATES',
  MAX_DISCOUNT_CODES = 'MAX_DISCOUNT_CODES',
  MAX_LANDING_PAGES = 'MAX_LANDING_PAGES',
  MAX_BLOG_POSTS = 'MAX_BLOG_POSTS',

  // Boolean access features
  CAN_USE_ADVANCED_TARGETING = 'CAN_USE_ADVANCED_TARGETING',
  CAN_USE_BLOGGING = 'CAN_USE_BLOGGING',
  CAN_USE_LANDING_PAGE_BUILDER = 'CAN_USE_LANDING_PAGE_BUILDER',
  CAN_USE_AFFILIATE_MARKETING = 'CAN_USE_AFFILIATE_MARKETING',
  CAN_USE_SEO_TOOLS = 'CAN_USE_SEO_TOOLS',
  CAN_USE_GIFT_OPTIONS = 'CAN_USE_GIFT_OPTIONS',
  CAN_USE_BOGO_PROMOTIONS = 'CAN_USE_BOGO_PROMOTIONS',
  CAN_USE_QUANTITY_DISCOUNTS = 'CAN_USE_QUANTITY_DISCOUNTS',
  CAN_USE_CUSTOM_BRANDING = 'CAN_USE_CUSTOM_BRANDING',
  CAN_ACCESS_APP_STORE = 'CAN_ACCESS_APP_STORE',
  CAN_USE_API_ACCESS = 'CAN_USE_API_ACCESS',
  // Add other features as needed
}